name: XiugouMessageProcessor

on:
  push:
    paths:
      - "src/Processors/MessageProcessor/**"
      - ".github/workflows/messageprocessor.yml"
  pull_request:
    paths:
      - "src/Processors/MessageProcessor/**"
      - ".github/workflows/messageprocessor.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV-TKE-1

    steps:
      - uses: actions/checkout@v2
      - id: log
        run: echo "commitmsg=$(git log --format=%B -n 1 ${{ github.event.after }} | sed -e 's/[^a-zA-Z0-9.-]/-/g' | tr '\n' '#' | sed -e 's/#.*//g' | head -c 100)" >> $GITHUB_ENV
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Install dependencies
        run: dotnet restore ./src/Processors/MessageProcessor/MessageProcessor.sln
      - name: Build
        run: dotnet build ./src/Processors/MessageProcessor/MessageProcessor.sln --configuration Release --no-restore
      - name: Tests
        run: dotnet test ./src/Processors/MessageProcessor/MessageProcessor.sln --no-restore --verbosity normal
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo $GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: "${{ secrets.TC_XIUGOU_DOCKER_USERNAME }}"
          password: "${{ secrets.TC_XIUGOU_DOCKER_PASSWORD  }}"
          registry: "xiugou-registry.tencentcloudcr.com"
          repository: "ns-hk/xiugou-repo"
          dockerfile: "./src/Processors/MessageProcessor/Dockerfile"
          push: ${{ github.ref == 'refs/heads/main' }}
          tag_with_sha: true
